version: 2
jobs:
  build:
    docker:
      - image: joshk0/resume
    steps:
      - checkout
      - run:
          name: generate resume pdf
          command: make
      - store_artifacts:
          path: resume.pdf
