version: 2
jobs:
  build:
    docker:
      - image: tianon/latex
    steps:
      - checkout
      - run:
          name: install extra fonts
          command: apt-get update && apt-get install texlive-fonts-extra fonts-font-awesome
      - run:
          name: LaTeX build
          command: latex resume.tex
      - run:
          name: PDF output
          command: dvipdfm resume.dvi
      - store_artifacts:
          path: resume.pdf
