version: 2
jobs:
  build:
    docker:
      - image: tianon/latex
    steps:
      - checkout
      - run:
          name: generate resume pdf
          command: make
      - store_artifacts:
          path: resume.pdf
